### ISSUE TITLE
Class logic is needed

### ISSUE THREAD

**Issue by PunyDevil** [ViRGiL175/git-starship#11]
We need:

- [ ] Universe process
- [ ] Base event stack
- [ ] Battle logic
- [ ] Trade logic

Universe process should include:

- [ ] Space traveling
- [ ] Random events
- [ ] Stats and states
- [ ] Wining and losing conditions

Event stack should include:

- [ ] Battle event
- [ ] Trade event

Battle logic should include:

- [ ] Gun logic
- [ ] Damage logic
- [ ] Ship types

Trade logic should include:

- [ ] Cash system
- [ ] Buy and sell system
- [ ] Item types
- [ ] Trader types

**Comment by ViRGiL175** [comment]
Very abstract.
