### ISSUE TITLE
Base event stack

### ISSUE THREAD

**Issue by PunyDevil** [ViRGiL175/git-starship#12]
Event stack is a event list, from which events are taken, in event put our ship, trades, enemies, locations etc.

Event stack should include:
- [ ] Battle event
    * Battles in differents locations
    * Battles with pirates of fetishists
    * Random Battles
- [ ] Trade event
    * Trade with different traders
    * Traders in special locations (sometimes randomly)

**Comment by ViRGiL175** [comment]
A more detailed description is needed.

**Comment by ViRGiL175** [comment]
Description is not perfect, but more or less clear. OK.
