### ISSUE TITLE
Item types

### ISSUE THREAD

**Issue by PunyDevil** [ViRGiL175/git-starship#15]
- [ ]        Magazine (include ammo)
- [ ]        ShipPart
              - Hull
              - Engine
- [ ]        Gun
              - Turret
              - Railgun
- [ ]        MedicineChest

**Comment by ViRGiL175** [comment]
Dirty markup.

More detailed description is needed.

**Comment by ViRGiL175** [comment]
It is very complex because of each command participation.
And Issue contain three big parts: ship parts, gun, medicine.

It should be splitted.

**Comment by ghost** [comment]
It was divided to: #17 and #16 (Medical chest was removed)
