### ISSUE TITLE
Ships

### ISSUE THREAD

**Issue by PunyDevil** [ViRGiL175/git-starship#24]
Ship - may be our starship or a ship of pirates
- [ ] Must have engine, hull, storage, HP.
  * storage may contains items
- [ ] They can attack another ships

**Comment by ViRGiL175** [comment]
And ship can land, loot, trade.

**Comment by ViRGiL175** [comment]
I can't work until #36 not fixed.

**Comment by ViRGiL175** [comment]
Can't work because of #43

**Comment by ViRGiL175** [comment]
Can't work because of #22

**Comment by ViRGiL175** [comment]
Closed with #51
