### ISSUE TITLE
Wrong Storage architecture

### ISSUE THREAD

**Issue by ViRGiL175** [ViRGiL175/git-starship#36]
`Storage` `putItem()` method should return `boolean`.

In case of `Storage` overfilling should return `false`. In case of successful putting -- `true`.

Fix for Java classes and UML is needed.

**Comment by ViRGiL175** [comment]
There are also `void` `getItem()` method! It's totally broken lol.

**Comment by ghost** [comment]
Fixed it!

**Comment by ViRGiL175** [comment]
@Alvahaze And..?
