### ISSUE TITLE
Class architecture is needed

### ISSUE THREAD

**Issue by ViRGiL175** [ViRGiL175/git-starship#6]
We don't have enough functionality and reasons for naming this system "Game". So I propose to use "Universe" term to describe high-level objects interaction logic.

We need:
- [x] Universe process architecture
- [x] Battle architecture
- [x] Trading architecture

Universe process should include:
- [x] Space traveling
- [x] Random events
- [x] Stats and states
- [x] Wining and losing conditions

Battle architecture should include:
- [x] Different guns with ammo
- - [x] Metal storage items usable as ammo for a Railgun
- [x] Damage and battle system 
- [ ] Looting system
- [x] Spaceship repairing system
- [x] Different types of Spaceships

Trading architecture should contain:
- [x] Storage system
- [x] Trading system
- [x] Trading locations
- [x] Valuable items

Also:
- [x] Create Issues for the Second Stage and partially for the Third Stage

UML file location: 
https://github.com/ViRGiL175/java-git-starship/blob/dev/src/main/resources/diagram_git_starship.puml

Feel free to discuss and create.

**Comment by ViRGiL175** [comment]
`iss6_gff_class_architecture` branch is created.

**Comment by ghost** [comment]
**ViRGiL175**, UML file link is broken.

**Comment by ViRGiL175** [comment]
Fixed.

**Comment by ViRGiL175** [comment]
Also we should create Issues for the Second Stage and partially for the Third Stage.

**Comment by AlexRakitskiy** [comment]
We have some commits in `iss6_raa_class_architecture` branch.

**Comment by ViRGiL175** [comment]
OK! I will look into in the morning.

**Comment by ViRGiL175** [comment]
Please, create `iss6_gff_class_architecture` <- `iss6_raa_class_architecture` Pull Request for handy reviewing. @AlexRakitskiy 

Keep in mind that those Pull Request should be **rebased**, not merged.

**Comment by AlexRakitskiy** [comment]
We have a starship that can traveling in space between locations and meeting random events from his way.

**Comment by AlexRakitskiy** [comment]
We have two base universe objects: starship and event.

**Comment by AlexRakitskiy** [comment]
Starship don't moving -- stack of events is moving.

**Comment by AlexRakitskiy** [comment]
Event is an opportunity for interaction of starship with other events objects.

**Comment by AlexRakitskiy** [comment]
Universe contain our Starship, stack of events and current event.

**Comment by ViRGiL175** [comment]
> Universe contain our Starship, stack of events and current event.

Is universe contain array of Planets, Places etc? Can we meet one Location few times? @AlexRakitskiy

**Comment by AlexRakitskiy** [comment]
> Is universe contain array of Planets, Places etc? Can we meet one Location few times? @AlexRakitskiy

No. All locations will be generated randomly.

**Comment by AlexRakitskiy** [comment]
The Spaceship must become a participant in the event.

**Comment by AlexRakitskiy** [comment]
Base Starship contain Hull, Engine, Storage, HP and Cash.

**Comment by ViRGiL175** [comment]
> Valuable items

There are no `IValuable` interface with `getCost()` method for trading! Alarm!

**Comment by ViRGiL175** [comment]
With pain and misery completed.
