### ISSUE TITLE
Game logic is needed

### ISSUE THREAD

**Issue by ghost** [ViRGiL175/git-starship#8]
Excellent! The first stage is complete, we're creating class architecture. Now we need to create a game logic, for the interaction of objects in our universe.

Universe process should include:
- [ ]  Base event stack

Battle logic should include:
- [ ]  Gun logic
- [ ]  Battle logic
- [ ]  Ship types

Trading architecture should contain:
- [ ]  Trade logic

Feel free to discuss and create.

**Comment by ViRGiL175** [comment]
Wrong Issue parameters and format. Also unnecessary.
